# This is the base dockerfile. Here the base image is pulled and the ras setup is done for the project.
# Make sure to include the base setup for lerna here.
FROM node:18 as base
WORKDIR /app
COPY . .
RUN npm install
COPY ./lerna.json ./
